### ISSUE TITLE
Update GA ID Code

### ISSUE THREAD

**Issue by blainehussey** [SolaceDev/solace-dev-codelabs-site#11]
Currently is pointing to our Solace.com GA ID, not Solace.dev.

**Comment by Mrc0113** [comment]
Just want to verify that it should be `UA-3921398-1`. correct? That is what's in use right now on the individual codelabs and in the tutorial to create a codelab

**Comment by Mrc0113** [comment]
@blainehussey - were you able to verify? 
we should also update the [DEFAULT_GA](https://github.com/SolaceDev/solace-dev-codelabs-site/blob/master/site/gulpfile.js#L44) const in the gulpfile

**Comment by blainehussey** [comment]
Hi @Mrc0113,
just dove into GA and it looks like it may be using the one for Solace.com;
Solace.com Tracking ID = UA-3921398-1
Solace.dev Tracking ID = UA-3921398-10

Thanks again.

**Comment by Mrc0113** [comment]
Fixed and forgot to put in commit comment 🤦‍♂ 
https://github.com/SolaceDev/solace-dev-codelabs-site/commit/429f7a1df477beff5fa10cc8a3c276231d69156b
