### ISSUE TITLE
Automate Submodule Update Process

### ISSUE THREAD

**Issue by Mrc0113** [SolaceDev/solace-dev-codelabs-site#12]
See if we can improve the process we currently use which is below: 
- Update codelab on DEV branch in solace-dev-codelabs
- PR it into master
- Approve PR & make sure DEV branch is up to date with master afterwards...
- Update solace-dev-codelabs submodule on DEV branch in solace-dev-codelabs-site
- PR it into master
- View Deploy Preview created by Netlify
- Approve PR & make sure DEV branch is up to date with master afterwards...

Maybe use github actions? Other?

**Comment by jerdog** [comment]
A few helpful links to get us started:

https://github.com/marketplace/actions/git-actions
https://github.com/marketplace/actions/checkout-submodules
https://github.com/marketplace/actions/bump-git-submodules

**Comment by jerdog** [comment]
I have requested GitHub Actions be added to solacedev org

**Comment by TamimiGitHub** [comment]
https://github.com/SolaceDev/solace-dev-codelabs/issues/32

**Comment by jerdog** [comment]
👏🏻 🎬 👏🏻
