### ISSUE TITLE
Landing page - "solace developers" icon to point to solace.dev

### ISSUE THREAD

**Issue by aaron-613** [SolaceDev/solace-dev-codelabs-site#36]
On the Solace Codelabs landing page, clicking on the "solace developers" graphic in the top-left corner points to `codelabs.solace.dev`.  I believe it should point to `solace.dev`.  Thanks!

**Comment by Mrc0113** [comment]
agree! That in conjunction with this #37 will help this feel like a subpage of solace.dev

**Comment by Mrc0113** [comment]
will be fixed as a larger overhaul of header revamp on dev sites
