### ISSUE TITLE
Stylize codelab tiles

### ISSUE THREAD

**Issue by jerdog** [SolaceDev/solace-dev-codelabs-site#7]
[Monday 4:20 PM] Marc DiPasquale
    
Also added link for resource on how to style tiles: https://groups.google.com/forum/#!topic/codelab-authors/zirJEyxRbFU

**Comment by Mrc0113** [comment]
More info on styling in the "Categorize Codelabs" section here: https://medium.com/@zarinlo/publish-technical-tutorials-in-google-codelab-format-b07ef76972cd
