### ISSUE TITLE
Allow solace.dev/codelabs to be served

### ISSUE THREAD

**Issue by jerdog** [SolaceDev/solace-dev-codelabs-site#9]

**Comment by blainehussey** [comment]
Reached out to Netlify about this, will keep you both posted on this.

**Comment by blainehussey** [comment]
https://community.netlify.com/t/common-issue-can-i-deploy-multiple-repositories-in-a-single-site/179

**Comment by jerdog** [comment]
So looks like it's just a proxy redirect? Even though it should just _work_? Because we're effectively already doing that here with our https://github.com/SolaceDev/solace-dev-codelabs inside of this repo and it's serving two repos into https://focused-beaver-3cc79d.netlify.com/.

So in theory we should be able to do the 

```git submodule add git@github.com:SolaceDev/solace-dev-codelabs-site.git codelabs```

in the solace-dev repo and it would work with the folder "codelabs" created to hold the repo...?

**Comment by blainehussey** [comment]
Thanks for taking a look at this @jerdog, it sounds pretty straight forward but at the same time I'll probably need your help to go through this and just ensure this gets setup correctly, could we schedule something Monday?

**Comment by jerdog** [comment]
sure. What steps have you done to test the solace.dev site locally? I want to try and verify this will work

**Comment by Mrc0113** [comment]
I read it a bit differently than @jerdog . It sounds to me like we should be able to keep the solace-dev-codelabs-site separate from solace-dev and just have a proxy redirect. 

If we go the submodule route everytime we update a codelab we would have to push changes to the solace-dev-codelabs repo, update the submodule in solace-dev-codelabs-site and then also update the submodule in solace-dev. I think it would be preferred to not have to do that last step if we can avoid it by keeping them separate which is how it came across to me.

**Comment by jerdog** [comment]
I believe we can setup a Github action to do all of that @Mrc0113 ? I haven't messed around with them, but I think so....

So right now, with the codelabs... If you push a new one, what process do you do? In theory we should just have to kick off a `Deploy` on Netlify which will do the syncing for us?

**Comment by Mrc0113** [comment]
Right now I do the following: 
* Update codelab on DEV branch in solace-dev-codelabs
* PR it into master
* Approve PR & make sure DEV branch is up to date with master afterwards...
* Update solace-dev-codelabs submodule on DEV branch in solace-dev-codelabs-site
* PR it into master 
* View Deploy Preview created by Netlify
* Approve PR & make sure DEV branch is up to date with master afterwards...

Kind of a pain so if we can improve that then it would be awesome..

**Comment by jerdog** [comment]
I think we need to look into GitHub actions... Something where a merge of a
PR in -codelabs kicks off an automerge on -codelabs-site, which would then
auto kick off a Netlify build.

**Comment by Mrc0113** [comment]
Agree: Created https://github.com/SolaceDev/solace-dev-codelabs-site/issues/12 to track that.

**Comment by blainehussey** [comment]
Hi Team, I was just looking into this again and came across some more details in their [docs](https://docs.netlify.com/routing/redirects/#syntax-for-the-redirects-file). Could one or both of you work with me to get this up and running, it sounds there's several ways of doing this but wanted to see if we can figure out what our best option is so I can close this one out. Thanks team.

**Comment by Mrc0113** [comment]
@blainehussey @jerdog 
Yes, I think we need to setup a working session with the 3 of us to see if we can get something working. I've tried a few things without success. I'm wondering if we are going to need to do something like this? https://docs.netlify.com/routing/redirects/rewrites-proxies/

**Comment by jerdog** [comment]
I think in the meantime we need to try the proxy rewrite and then we can work on other things in the future when we have time (using GitHub Actions, etc.).

Alternatively... couldn't we just have the Codelab netlify site answer to https://solace.dev/codelabs? Or is that what we're meaning with the proxy rewrite?

**Comment by blainehussey** [comment]
@Mrc0113 and @jerdog I'm closing this one as I don't believe it's still relevant, if I'm misunderstood though, please reopen.

**Comment by jerdog** [comment]
To close this out, what we did was setup `codelabs.solace.dev` and have `solace.dev/codelabs` redirect there.
